name: windows-latest Developement Build

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup WSL
      uses: Vampire/setup-wsl@v3
      with:
        distribution: Ubuntu-22.04

    - name: Update ubuntu
      shell: wsl-bash {0}
      run: |
        sudo apt update
        sudo apt search qt6
        sudo apt install -y \
          build-essential \
          cmake \
          pkg-config \
          qt6-base-dev \
          qt6-base-dev-tools \
          libqt6charts6-dev \
          libqt6svg6-dev \
          libgl1-mesa-dev \
          libxkbcommon-dev \
          libxcb-xinerama0-dev \
          libxcb-cursor-dev

    - name: Where Am I
      shell: wsl-bash {0}
      run: |
        pwd
        ls -l
        lscpu

    - name: Versions
      shell: wsl-bash {0}
      run: g++ --version

    - name: Configure CMake
      shell: wsl-bash {0}
      run: |
        cd src/build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DQTVERSION=QT6 \
          -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6

    - name: Build
      shell: wsl-bash {0}
      run: |
        cd src/build
        make -j$(nproc)

    - name: Tar
      shell: wsl-bash {0}
      run: |
        cd src/build
        cp ../../LICENSE .
        cp ../../CHANGELOG.md .
        tar zcvf seergdb.tar.gz LICENSE CHANGELOG.md seergdb

    - name: List Results
      shell: wsl-bash {0}
      run: |
        cd src
        ls -l build/

