name: windows-latest Developement Build

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up WSL and build in Ubuntu
        shell: wsl-bash {0}
        run: |
          # Ensure your WSL is Ubuntu, otherwise adjust this step accordingly.
          echo "WSL Distro: $(lsb_release -d)"

          # Set up Qt environment if needed
          # You can replace this with a proper path if installed manually
          export PATH=/opt/Qt/6.6.2/gcc_64/bin:$PATH
          export CMAKE_PREFIX_PATH=/opt/Qt/6.6.2/gcc_64

          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Qt6-App-Binaries
          path: build/

